<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
            <a class="navbar-brand" href="#" id="">ECTS CMP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="ECTS-MainPage.php">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Games & Tools</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="Student-Reviews.php">Student Reviews</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Additional Resources</a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="Local-Industry.php">Local Industry Support</a>
                            <a class="dropdown-item" href="Apply-Page.php">Apply</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="https://www.ects.org/" target="blank" >Official ECTS Website</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>